name: "新功能提案"
description: "对已有功能的大幅度修改，或添加一个新内容或选项。"
type: "新功能"
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "我已在 [Issues 页面](https://github.com/PCL-Community/PCL2-CE/issues?q=is%3Aissue+) 中搜索，确认了这一提案未在社区版被提交过"
      required: true
    - label: "我确认只是全部选中而没有[仔细确认](https://github.com/PCL-Community/PCL2-CE/issues?q=is%3Aissue+)就直接提交了这个 Issue，并且同意这个 Issue 可以直接被关闭"
      required: false
    - label: "我确认我的提案是对某一个具体功能，而不是一堆功能要求挤在一个 Issue 里"
      required: true
    - label: "我已知悉本项目的开发者均为不带薪志愿者，社区不对这类 Issue 的完成时间作出任何保证，并有足够的耐心等待社区开发者的处理，同时已知悉如果我作出催促、质问或类似的举动，这个 Issue 可能会被直接关闭"
      required: true
- type: input
  id: "yml-2"
  attributes:
    label: "官方版原 Issue 编号"
    description: "如果这个 Issue 是从官方版转交过来的，请将原 Issue 标题旁的**编号**输入到下方预设文本的`#`后，不要输入任何其他非数字字符。**若不是，请清空下方输入框。**"
    value: "- Meloong-Git/PCL2#"
- type: textarea
  id: "yml-3"
  attributes:
    label: 描述
    description: "详细描述你想添加的功能具体是怎样的。"
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: 原因
    description: "详细描述你为什么需要这项功能，这有助于开发者评估它的优先度。"
    placeholder: |
      示例：
      我需要这个功能来xxxx，如果没有这个功能，就不能xxxx了。
  validations:
    required: false
